# Hardening and Obfuscation Rules for Penny Budgeting
# Generated by Senior Security Mobile Developer

# 1. Base Obfuscation & Hardening
-renamesourcefileattribute SourceFile
-keepattributes !SourceFile,!LineNumberTable,!Signature,!LocalVariableTable,!LocalVariableTypeTable,!MethodParameters,!RuntimeVisibleAnnotations,!RuntimeInvisibleAnnotations,!RuntimeVisibleParameterAnnotations,!RuntimeInvisibleParameterAnnotations,!AnnotationDefault
-repackageclasses ''
-allowaccessmodification
-dontusemixedcaseclassnames
-overloadaggressively

# 6. Prevent Decompilation hints
-dontpreverify
-optimizationpasses 5
-useuniqueclassmembernames
-flattenpackagehierarchy ''

# 7. Aggressive Obfuscation
-overloadaggressively
-repackageclasses ''
-allowaccessmodification

# 2. Capacitor Bridge Protection (MANDATORY)
# We must keep Capacitor-specific bridge classes to prevent JS-to-Native crashes
-keep class com.getcapacitor.** { *; }
-keep interface com.getcapacitor.** { *; }
-keep class * extends com.getcapacitor.Plugin { *; }
-keep class * extends com.getcapacitor.BridgeActivity { *; }

# 3. Native Biometric Plugin Protection
-keep class com.zoom.capacitor.biometric.** { *; }

# 4. Remove Logs for Release (Security hardening)
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
    public static *** w(...);
    public static *** e(...);
}

# 5. Generic Protection for Android support libraries
-keep class androidx.** { *; }
-keep interface androidx.** { *; }
-dontwarn androidx.**
